### ISSUE TITLE
Make a button

### ISSUE THREAD

**Issue by MineRobber9000** [MineRobber9000/neowiki#12]
We should have a button. Netscape style or not? (Probably not, since that's a bit cliche, and I'm pushing it with my own button) Other design stuff will need to be decided before we can make a button.

**Comment by yoshi295295** [comment]
do something creative

**Comment by MineRobber9000** [comment]
We're going to use the 5 button designs submitted by hellgradeer in the Discord.
![spacegreen](https://user-images.githubusercontent.com/12676241/46263874-45a71c00-c4e3-11e8-8295-5685baa3726a.gif)
![spaceblue](https://user-images.githubusercontent.com/12676241/46263875-45a71c00-c4e3-11e8-833f-fa1dced699eb.gif)
![spacedusk](https://user-images.githubusercontent.com/12676241/46263878-45a71c00-c4e3-11e8-9562-026f69a9b2ea.gif)
![logoblue](https://user-images.githubusercontent.com/12676241/46263876-45a71c00-c4e3-11e8-8931-d0a2cc05753e.gif)
![logogreen](https://user-images.githubusercontent.com/12676241/46263877-45a71c00-c4e3-11e8-8bc0-07eb925fb689.gif)
